dashboard/urls.py
from django.urls import path

from .views import *

app_name = 'dashboard'

urlpatterns = [
    path('', home, name='home'),    
]

journal/urls.py
from django.urls import path
from .views import *

app_name = 'journal'

urlpatterns = [
    path('add', add_journal, name='add-journal'),
    path('edit/<str:id>', edit_journal, name='edit-journal'),
    path('delete/<str:id>', delete_journal, name='delete-journal'),
    path('view/<str:id>', view_journal, name='view-journal'),
    path('view-all', view_all_journals, name='view-all-journals'),
    path('calendar/', default_calendar_view, name='default_calendar_view'),
    path('calendar/<int:year>/<int:month>/', calendar_view, name='calendar_view'),
    
]

journal_guard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('', include('dashboard.urls')),
    path('journal/', include('journal.urls')),
    path('accounts/', include('allauth.urls')),
]

user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import *

urlpatterns = [
    path('register/', Register.as_view(), name='register'),
    path('register-options/', registration_options, name='register-options'),
    path('email_verification/<str:uidb64>/<str:token>', email_verification, name='email-verification'),
    path('email_verification_sent/', email_verification_sent, name='email-verification-sent'),
    path('email_verification_success/', email_verification_success, name='email-verification-success'),
    path('email_verification_failed/', email_verification_failed, name='email-verification-failed'),

    path('login/', Login.as_view(), name='login'),
    path('logout/', user_logout, name='logout'),
    
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='user/password/password-reset.html'), name='password_reset'),
    path('password_reset_sent/', auth_views.PasswordResetDoneView.as_view(template_name='user/password/password-reset-sent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='user/password/password-reset-form.html'), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='user/password/password-reset-complete.html'), name='password_reset_complete'),
    
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render
from django.utils.html import strip_tags
from django.utils import timezone
import pytz

from journal.models import Journal
from journal.utils import decrypt

def home(request):
    if not request.user.is_authenticated:
        return render(request, 'dashboard/home.html')
    journal = Journal.objects.filter(user=request.user).order_by('-created_at')[:10]
    user_timezone = request.COOKIES.get('timezone')
    if user_timezone:
        timezone.activate(pytz.timezone(user_timezone))
    for entry in journal:
        entry.content = decrypt(request, entry.content)
        entry.content = strip_tags(entry.content)
        entry.content = entry.content[:100] + '...'
    return render(request, 'dashboard/home.html', {'journal': journal})

dashboard/templates/dashboard/entry_card.html
<div class="">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-10">
                    <a href="{% url 'journal:view-journal' entry.id %}" class="">
                    <h5 class="card-title">{{ entry.title }}</h5>
                    </a>
                    <span class="text-secondary">Posted on {{ entry.created_at }}</span>
                    <p class="card-text">{{ entry.content }}</p>
                </div>
                <div class="col-md-2">
                    <div class="float-end btn-group dropend">
                        <a class="float-end p-2" role="button" id="dropdownMenu" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span><i class="float-end fa-solid fa-ellipsis-vertical"></i></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'journal:view-journal' entry.id %}">View</a></li>
                            <li><a class="dropdown-item" href="{% url 'journal:edit-journal' entry.id %}">Edit</a></li>
                            <li><a class="dropdown-item" href="{% url 'journal:delete-journal' entry.id %}">Delete</a></li>
                        </ul>
                    </div>          
                </div>
            </div>
        </div>
    </div>
</div>

dashboard/templates/dashboard/home.html
{% extends 'base.html' %}

{% block content %}
<style>

    a {
        text-decoration: none;
        color: black;
    }

    a:hover {
        text-decoration: none;
        color: black;
    }

</style>

{% if user.is_authenticated %}
<div class="container">
    <h1> My Journal </h1>

    <div class="row">
        <p class="col-md-3"> Your journal entries </p>
        <a href="{% url 'journal:add-journal' %}" class="col-md-2 offset-7 float-end btn btn-primary"> Create a new entry </a>
    </div>
    <br>
    <br>
    <div class="row">
        <div class="col-md-5">
        {% for entry in journal %}
            {% include 'dashboard/entry_card.html' %}
            <br>
        {% empty %}
            <p> You have no entries </p>
        {% endfor %}
        </div>
    </div>
</div>
{% else %}
<div class="container">
    <h1> Home </h1>
    <p> This is the home page </p>

    <a href="{% url 'journal:add-journal' %}" class="btn btn-primary"> Create a new entry </a>
    
</div>
{% endif %}
{% endblock %}