journal/urls.py
from django.urls import path
from .views import *

app_name = 'journal'

urlpatterns = [
    path('add', add_journal, name='add-journal'),
    path('edit/<str:id>', edit_journal, name='edit-journal'),
    path('delete/<str:id>', delete_journal, name='delete-journal'),
    path('view/<str:id>', view_journal, name='view-journal'),
    path('view-all', view_all_journals, name='view-all-journals'),
    path('calendar/', default_calendar_view, name='default_calendar_view'),
    path('calendar/<int:year>/<int:month>/', calendar_view, name='calendar_view'),
    
]

journal_guard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('', include('dashboard.urls')),
    path('journal/', include('journal.urls')),
    path('accounts/', include('allauth.urls')),
]

user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import *

urlpatterns = [
    path('register/', Register.as_view(), name='register'),
    path('register-options/', registration_options, name='register-options'),
    path('email_verification/<str:uidb64>/<str:token>', email_verification, name='email-verification'),
    path('email_verification_sent/', email_verification_sent, name='email-verification-sent'),
    path('email_verification_success/', email_verification_success, name='email-verification-success'),
    path('email_verification_failed/', email_verification_failed, name='email-verification-failed'),

    path('login/', Login.as_view(), name='login'),
    path('logout/', user_logout, name='logout'),
    
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='user/password/password-reset.html'), name='password_reset'),
    path('password_reset_sent/', auth_views.PasswordResetDoneView.as_view(template_name='user/password/password-reset-sent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='user/password/password-reset-form.html'), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='user/password/password-reset-complete.html'), name='password_reset_complete'),
    
]

templates/base.html
{% load static %}
{% load socialaccount %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://kit.fontawesome.com/4ff5184705.js" crossorigin="anonymous"></script>
    <title>Journal Guard</title>
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon.ico' %}">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">

</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        &nbsp;
        <a class="navbar-brand" href="#">Journal Guard</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">

            {% block navbar %}
            <ul class="navbar-nav">
                <li class="nav-item active ">
                    <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active ">
                    <a class="nav-link" href="{% url 'journal:default_calendar_view' %}">Calendar <span class="sr-only">(current)</span></a>
                </li>
            </ul>
            
            {% endblock navbar %}


            <ul class="navbar-nav ms-auto">
                &nbsp;
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="btn btn-alert navbar-btn text-white nav-anchor-link" type="button"  href="{% url 'account_logout' %}"> <i class="fa fa-sign-out"></i> &nbsp; Logout </a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="btn btn-alert navbar-btn text-white nav-anchor-link" type="button"  href="{% url 'login' %}"> Login </a>
                    </li>
                    <li class="nav-item">
                        <a class="btn btn-alert navbar-btn text-white nav-anchor-link" type="button"  href="{% url 'register-options' %}"> Get Started </a>
                    </li>
                {% endif %}
                &nbsp;
            </ul>
        </div>
    </nav>

    {% for message in messages %}
    
        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
        
            <h6 id="message-timer" class="alert alert-success text-center">{{message}}</h6>
        
        {% endif %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
        
            <h6 id="message-timer" class="alert alert-info text-center">{{message}}</h6>

        {% endif %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        
            <h6 id="message-timer" class="alert alert-danger text-center">{{message}}</h6>

        {% endif %}
    
    {% endfor %}
    
    <br>

    {% block content %}

    {% endblock content %}

    <br>

    <style>
        .nav-anchor-link {
            text-decoration: none;
            color: black;
        }
    </style>

</body>
    <script src="{% static 'js/app.js' %}"></script>
</html>